apiVersion: v1
kind: Service
metadata:
  name: {{ include "ResumeAI.fullname" . }}-backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.backEnd.containerPort }}
      targetPort: {{ .Values.backEnd.containerPort }}
  selector:
    app: {{ include "ResumeAI.name" . }}-backend
