apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ResumeAI.fullname" . }}-backend
  labels:
    app: {{ include "ResumeAI.name" . }}-backend
    chart: ResumeAI-0.1.0
    release: release-name
    heritage: Helm
spec:
  replicas: {{ .Values.backEnd.replicaCount }}  # Make sure this is defined in values.yaml
  selector:
    matchLabels:
      app: {{ include "ResumeAI.name" . }}-backend  # Correct this line
  template:
    metadata:
      labels:
        app: {{ include "ResumeAI.name" . }}-backend  # Ensure consistency
    spec:
      containers:
        - name: resumeaibackend
          image: "{{ .Values.backEnd.image }}"  # Ensure this is defined in values.yaml
          env:
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "ResumeAI.fullname" . }}-secrets
                  key: JWT_SECRET_KEY
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "ResumeAI.fullname" . }}-secrets
                  key: MONGO_URL
            - name: OPENAI_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "ResumeAI.fullname" . }}-secrets
                  key: OPENAI_KEY
            - name: GMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "ResumeAI.fullname" . }}-secrets
                  key: GMAIL_USER
            - name: GMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "ResumeAI.fullname" . }}-secrets
                  key: GMAIL_PASS
            - name: FRONT_END
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ResumeAI.fullname" . }}-config
                  key: FRONT_END
          ports:
            - containerPort: {{ .Values.backEnd.containerPort }}  # Ensure this is defined
